backend:
  name: git-gateway
  repo: cameronaziz/cameron-aziz-blog
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "post"
    label: "Post"
    folder: "data/posts"
    create: true
    format: json
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - label: "State"
        name: "state"
        widget: "select"
        default: "draft"
        options:
          - label: "Live"
            value: "live"
          - label: "Complete"
            value: "complete"
          - label: "Draft"
            value: "draft"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Spotlight Image"
        name: "spotlight-image"
        widget: "image"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "images"
    label: "Image"
    folder: "../../data/images"
    create: true
    format: json
    fields:
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
        files: "data/images"
        media_library:
          config:
            multiple: true
      - label: "Title"
        name: "title"
        widget: "string"
        required: false
      - label: "Alt Text"
        name: "alt-text"
        widget: "string"
        required: false
